// Auto-generated assembly info - Version comes from Directory.Build.props
using System.Reflection;
using System.Runtime.CompilerServices;

// Version attributes are generated by MSBuild from Directory.Build.props
// This file exists to ensure assembly metadata is properly embedded

[assembly: InternalsVisibleTo("BIBIM_MVP.Tests")]
